
export const data={
    'classic':[
    {
        id:1,
        name:'Naruto',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreie5broqaul7do5f4xjapsjpz2klca64zs6rdi6mb26m7zpsclth5u",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreihdp44wwyawwoswmzjrvik3fnvbi3xkqotsh3ugebznsg5mh2i3xe"
        
    },
    {
        id:2,
        name:'Sasuke',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreiadiyokv7q26t24gmo4imzyzcwijgtspvgo4ndcshvz5unwfpwx5u",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreiay6c424faqh52oh3z4aixjfxjeup4lw5wapyctuj6ewlbm33pczq"
    },
    {
        id:3,
        name:'Sakura',
        type:'Medic',
        rating:2,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreic5cggdmwd2tjsuzk262wz27lpwsvcqk4jptviivpvaykbk3cj5mi",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreigc7pl2ersr5nk4tfao2kifmcceujqtiesfjsgxwetkrrgkkkiugy"
    },
    {
        id:4,
        name:'Kakashi',
        type:'Ninjutsu',
        rating:4,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreifzahf6knfaqu43ya6kjtgoj4hyytskhigrbpmoc7yg3zoecov74q",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreihgdxg6qafpd3lav4tbjabz7tnooghu4kphffzfh5u6e4meos46ri"
    },
    {
        id:5,
        name:'Guy',
        type:'Taijutsu',
        rating:4,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreidawpd2z5xymzinl625l35aebaqyhw64cn4ysfahl6airjcgokre4",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreictankq3poi2zcyfh6iezcwd3q55htzmie3qno3lewoo2rzhix3qe"
    },
    {
        id:6,
        name:'Rock Lee',
        type:'Taijutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreig7dmxotvmnqddcs5hzxho3qasvfkciw6ftf6bab365scbg75n6ha",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreih5ilirtzmlssnpb7giapvcicwvlewnvbrp2lydwk6rm2ilp64tmi"
    },
    {
        id:7,
        name:'Neji',
        type:'Dojutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreib6zhmftv3junn5yiw67wlemvuhmyqujnl2xieoved227cmxurrs4",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreiah3moquqph62gnctzfwy4x2qrg4q4x5gijbljshvweouctkpc3li"
    },
    {
        id:8,
        name:'Asuma',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreihile76qrpxk5cfndmltl4eln277c33ifs6uupn4ikrikkv2fem44",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreih6a7hk3jn3uc4fly2ctsxcwtiydlyoffenpoljtz2ph5mzlcw6bi"
    },
    {
        id:9,
        name:'Shikamaru',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreiavuzjbatr5qysk3r4hs4ubku7up7faauirnbzwq46iiwibavzr5a",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreieufngpqonpo5nxaacqwwnbxydur3foelv2z6wujkvb4zkyj4rqp4"
    },
    {
        id:10,
        name:'Choji',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreihbohgydxumzkarn3oxtjblzcgicbtddzpqo424u2saaucf2hchvq",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreihkod2cskc5iy47cilpycygaqwdxvcrze4p56eew4oatb5cvigw6q"
    },
    {
        id:11,
        name:'Ino',
        type:'Ninjutsu',
        rating:2,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreie6nhffr7v665g7j3yi2bhkwkwbt5kcb5zyisam3idbmr3764yulq",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreid3f5quibbsjgazzx3oeaslbb6d64twm4jokndakgzcethaag7zua"
    },
    {
        id:12,
        name:'Kurenai',
        type:'Genjutsu',
        rating:2,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreicnrrayz4dwixgkswk74ihpbcwhxx3yv7effac6yzt77fuwby7pui",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreicoqxrvovdclagtsllkgseyca2awgisixboccj3p3smfdagcjwobm"
    },
    {
        id:13,
        name:'Hinata',
        type:'Dojutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreifvdf5rypculvpxp5iocrfsumnvi6jx64u3hau2xizjfblj2qrhfa",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreia7zx3esvehrnhgwn4dw4472xldrnpeoy65gocqjrzottjb2rm44m"
    },
    {
        id:14,
        name:'Shino',
        type:'Ninjutsu',
        rating:2.5,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreiamoizsciiuchaexe6gra3ancxxgj3263fc6x6qgskiyczazwkczi",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreig63gjgonzlyi3xfuh4dqyybaqrielqzwgtahkuydyhgoqx75kru4"
    },
    {

        id:15,
        name:'Kiba',
        type:'Ninjutsu',
        rating:2,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreih5fkf2obicvl4acirvr5nshqk4sqqz4dfehhvybstlcry34m7xdi",
        url:" https://eu.starton-ipfs.com/ipfs/bafkreihsj6cwiampjiyhsidoran7vxa53d7ivsv3k2ng4ssfj2tnhiqybe"
    },
   


],
'akatsuki':[
    {
        id:1,
        name:'Itachi',
        type:'Dojutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreicdy5q4vn222hzlm2fgvfj3gf52jgfmznftjs7q6d2ez5qx22kwge",
        url:" https://eu.starton-ipfs.com/ipfs/bafkreie45scssa45f7wr2wjiro2f47yq5nk5xf3a7usrz4phg2ouqegooy"
        
    },
    {
        id:2,
        name:'Konan',
        type:'Ninjutsu',
        rating:4.5,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreibyzd3qwr3mrijr3cdulofkgclcimradsrwq7ggbhnov47qbwrd5y",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreibiuuuz4il2jqp3f3zagc2uto5litllm2lxq5r3jjjp4g3f3jqpiy"
    },
    {
        id:3,
        name:'Sasori',
        type:'Bukijutsu',
        rating:3.5,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreia2shl3mlwx3y3usecz4tcj4hqienp3ta4sh7wfea2q3ju4nbe2gm",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreicdsnc3xh5xalh7mwaub2gwnni5lvuo2upco6m3ldspdify52dyyi"
    },
    {
        id:4,
        name:'Deidara',
        type:'Bukijutsu',
        rating:3.5,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreickz7kfytokco6dljwbs5yothrdlzsssmf3pwxug6eybyxsn4rksu",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreiavrgw27oezvlz4hagg226mycv2h6mw5vpqfiesfvopkqmviiite4"
    },
    {
        id:5,
        name:'Kisame',
        type:'Ninjutsu',
        rating:4,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreigsnkrurbcdpzox5y5s7gjczxyqigvuxdnqpurmsrbduk42m5fxkq",
        url:" https://eu.starton-ipfs.com/ipfs/bafkreicxmwi3c2uq5xqx6nc5makbjlzmaxaumpv2ruq3kytypb7e3tar3y"
    },
    {
        id:6,
        name:'Pain',
        type:'Dojutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafybeig6bfqr5nrge4xp5qquiu7tyvcvh6zfsrr2vjjg5jjbjzb75cyf4q",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreibqu772xj6zf7q7upwacsia2drlhnc7bcqwlb7sbtyuqf5bvjxbau"
    },
    {
        id:7,
        name:'Tobi',
        type:'Dojutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreib66aud2oxosjai4aykbpdhflg3z36lo7lze2rytd7ptohf7habv4",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreihm6otc3ye5dkz37gjyt24zigbqfegeqdj7qn3bq72kkpnhwnunke"
    },
    {
        id:8,
        name:'Hidan',
        type:'Jujutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreia4oflwzs2ubfrqmxfu3ce7yogxeo75o6ymghon3bhgr5fs23nosa",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreibi76necekrbfuyt5kbxnxxiid63gzoigx5h6jl4wlkftgautor4y"
    },
    {
        id:9,
        name:'Kakuzu',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://eu.starton-ipfs.com/ipfs/bafkreie6fzjhn2yx6uuvpykajasvnpfe72uiyajim3fj6xrwwyl66f2d7m",
        url:"https://eu.starton-ipfs.com/ipfs/bafkreiarnrxcitcczv5so6sfq5mbhtm6a7rfdr3g57kalabkj7jhzd2eaa"
    },
]


}

